# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-08 10:04
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('attack', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('protec', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('poison', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('regene', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('tactic', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Character')),
            ],
        ),
    ]
